### PR TITLE
Text header for blackboard.

### PR DESCRIPTION
**Pull request by drbalar**
For any blackboard object, this will work. Currently text and color can be modified. Color is white by default.
The text will show on the top of the puzzles. It will auto resize based on the amount of text and wrap around if needed. About 25-30 words is the limit right now before we overflow off the cameraview.

Below are different scenarios of the blackboard puzzles. 

image
image
image
image

### CODE REVIEW

**Comment by drbalar** [comment]
Also for keypad puzzle, SOLVED and ERROR also use the same text. 

image
image

**Review by jaydhulia — APPROVED** [review]
Nice work @drbalar, works great and looks good to me 🎉

**Comment by ahmedhamodi** [comment]
Love the detailed images showing the text. Looks good to me from a end-user perspective :)

**Review by ahmedhamodi — APPROVED** [review]

**Comment by aaronabraham311** [comment]
Thank you Dhruvin, really nice work!

**Pull request merged**
