### PR TITLE
Room 3 Updates

### PR DESCRIPTION
**Pull request by vivianliu0**
- Updated jigsaw puzzle image
- Removed picture frames that do not contain a hidden letter
- Updated picture frame with letter "O" (frame 3 from the right)
- Reached out to Dhruvin about updating the glb file of frame 3 to have the new image displayed
Loom Demo: https://www.loom.com/share/883a0387b0844184808a1e89f2dbddf5

### CODE REVIEW

**Review by ahmedhamodi — COMMENTED** [review]
Code looks good to me.

Question though, why did we update the image with the "O" in it? Was it too easy?

**Review by aaronabraham311 — COMMENTED** [review]
If you can't get the following comments done by Friday, I can action it off as a later ticket. 
1. The image is still the O image when you look at it in the room (the object is not a frame around a baseball stadium, it's a frame around the letter image)
2. The O in the picture is quite difficult for people with color difficulties to find. Perhaps try hiding the O in the grass?

**Comment by jaydhulia** [comment]
@vivianliu0 The frame seems different than the pic when you click on the image (for the O), did you get a chance to update it?

**Comment by vivianliu0** [comment]
in response to aaron and jay, Dhruvin just sent me the updated glb file so I will update the AWS with the new file now

**Comment by jaydhulia** [comment]
Thanks @vivianliu0. Can you also update the corresponding local file to the updated glb? Should be the same GLB file name inside `app/public/static/assets/` folder

**Comment by vivianliu0** [comment]
Updated demo: https://www.loom.com/share/4fe39f0f79f142ec9468d78f3cc047ca
- glb frame is updated
- updated baseball image so that the hidden "O" is more obvious

**Review by aaronabraham311 — APPROVED** [review]
Product approval. Nice work!

**Review by ahmedhamodi — DISMISSED** [review]
Code approval :D

**Review by jaydhulia — CHANGES_REQUESTED** [review]
Room looks great to me, tried it locally, one quick thing though. This file: 516ac4df01e44541b7dd7b575b183ce2.glb is missing in the repo, meaning the page doesn't load with local config. Can you please push that to `app/public/static/assets/516ac4df01e44541b7dd7b575b183ce2.glb`? Thanks @vivianliu0

**Comment by vivianliu0** [comment]
> Room looks great to me, tried it locally, one quick thing though. This file: 516ac4df01e44541b7dd7b575b183ce2.glb is missing in the repo, meaning the page doesn't load with local config. Can you please push that to `app/public/static/assets/516ac4df01e44541b7dd7b575b183ce2.glb`? Thanks @vivianliu0

Oops sorry about that, the file didn't get added to the commit. Updated

**Comment by vivianliu0** [comment]
> Question though, why did we update the image with the "O" in it? Was it too easy?

I think so, although @aaronabraham311 can confirm

**Review by jaydhulia — APPROVED** [review]
Awesome, nice work Vivian! Looks great to me! Let's 🚢

**Pull request merged**
