### PR TITLE
Fix X Button Position on Modal

### PR DESCRIPTION
**Pull request by vivianliu0**
Image of text pane:
image

### CODE REVIEW

**Review by aaronabraham311 — APPROVED** [review]

**Review by ahmedhamodi — COMMENTED** [review]
I might be being too picky but it seems too low? The distance from top > distance from left side 😅 I feel like 6.3 or 6.35 might be better.

**Comment by vivianliu0** [comment]
> I might be being too picky but it seems too low? The distance from top > distance from left side 😅 I feel like 6.3 or 6.35 might be better.

Sure I can update this, I noticed that the spacing of the Prev and Next button was greater for the bottom margin so I kept it consistent. I'll change them to all have the same distance from the edges

**Comment by vivianliu0** [comment]
> > I might be being too picky but it seems too low? The distance from top > distance from left side 😅 I feel like 6.3 or 6.35 might be better.
> 
> Sure I can update this, I noticed that the spacing of the Prev and Next button was greater for the bottom margin so I kept it consistent. I'll change them to all have the same distance from the edges

Updated image in description which reflects new changes

**Review by jaydhulia — APPROVED** [review]
LGTM!

**Review by ahmedhamodi — APPROVED** [review]

**Pull request merged**
