### PR TITLE
Inter-scene Transition

### PR DESCRIPTION
**Pull request by vivianliu0**
Loom demo:
https://www.loom.com/share/60116d4894f74c25bc02666bc2ac1c9a

### CODE REVIEW

**Comment by aaronabraham311** [comment]
Awesome work Vivian! This is what we wanted. 

Couple of comments:
- The number and content of transitions are specified by the DB, correct?
- Can we reduce the solved time to 2 seconds?

**Comment by vivianliu0** [comment]
@aaronabraham311 
> * The number and content of transitions are specified by the DB, correct?
Yep, the content is being pulled from the DB with our mock data

> * Can we reduce the solved time to 2 seconds?
Updated solved time to 2 seconds.

**Review by ahmedhamodi — COMMENTED** [review]
This looks good from an end user perspective! I also agree with Aaron, 2 seconds is better.

Will leave code quality review to Jay and Dhruvin :)

**Review by jaydhulia — APPROVED** [review]
Made some minor changes because the admin pages weren't working on this PR, but awesome work as usual @drbalar @vivianliu0! Ship it 🎉

**Pull request merged**
