### PR TITLE
Dhruvin room 4

### PR DESCRIPTION
**Pull request by drbalar**
Loom: https://www.loom.com/share/1d6b7942860a430686b82a68d335c275

I did not push the assets to this PR since they will be renamed/removed eventually.
Like last time, once approved in design terms, i will add assets and images to s3 and update PR

### CODE REVIEW

**Review by aaronabraham311 — DISMISSED** [review]
Product approval

**Comment by ahmedhamodi** [comment]
The confetti 😂 

No comments from me, will leave code review for Jay when he gets a chance. I really like the room!

**Comment by jaydhulia** [comment]
Not much to review for the code here tbh, let's just get all the assets into S3, merge this in, and test in production 😄

**Review by jaydhulia — CHANGES_REQUESTED** [review]
@drbalar the insert script doesn't work after the latest merge from the master, because there were some assets moving around / deleted. So doing `make install` now throws an error because assets aren't in created with the expected ID. Do you mind fixing that? 
And then I can test it out locally. Thanks

**Comment by drbalar** [comment]
@jaydhulia Fixed the IDs to match the new data. Should work now, let me know if it does not still for you

**Review by jaydhulia — APPROVED** [review]
LGTM!

**Pull request merged**
